# Generated by Django 4.0.3 on 2022-05-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_crud'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_mark_returned', 'Set pet as returned'),),
            },
        ),
    ]
